services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\ApiContext:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $client: '@test.client'

    App\Tests\Behat\CityFixtureContext:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Tests\Behat\AddressFixtureContext:
        arguments:
            $addressProvider: '@App\Tests\Fake\FakeAddressProvider'

    App\Tests\Fake\FakeAddressProvider:
        public: true

    App\Domain\Address\Port\AddressProviderInterface:
        alias: App\Tests\Fake\FakeAddressProvider
